about/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import about_view, AboutViewSet, CertificateView

app_name = 'about'

router = DefaultRouter()
router.register(prefix=r'about-us', viewset=AboutViewSet)
router.register(r'Certificate', CertificateView, basename='Certificate')

# use http://127.0.0.1:8000/about/about-us/delete_all/ with method DELETE to call delete_all function


urlpatterns = [
    path('api/', include(router.urls)),
    path("", about_view, name='view'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.conf.urls.static import static
from django.urls import path

from IranianShiningPhoenix import settings
from .views import *


app_name = 'contact'

urlpatterns = [

    path("", contact_view, name='view'),
    path('api/', EmailView.as_view(), name='email'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import home_view, SliderViewSet, CeoViewSet


app_name = 'home'
router = DefaultRouter()
router.register(r'slider', SliderViewSet)
router.register(r'CEO', CeoViewSet)


urlpatterns = [
    path("", home_view, name='view'),
    path("api/", include(router.urls)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ProductViewSet, product_view

app_name = 'product'

router = DefaultRouter()
router.register(r'products-view', ProductViewSet)
# products bulk delete: http://127.0.0.1:8000/products/products-view/delete_all/
# for filter products by category: http://127.0.0.1:8000/products/products-view/?categories=2
# in product app for filtering by categories developed by django-filter package in view.py

urlpatterns = [
    path('api/', include(router.urls)),
    path("", product_view, name='view'),

]

seo/urls.py
from django.urls import path, include
from .views import ArticleViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(prefix=r'article-view', viewset=ArticleViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
]

services/urls.py
from django.conf.urls.static import static
from django.urls import path

from IranianShiningPhoenix import settings
from .views import *


app_name = 'services'

urlpatterns = [
    path('api/service/', ServicesCreateView.as_view(), name='create-service'),
    path('api/service/update/<int:pk>/', ServicesDetailView.as_view({'put': 'update'}), name='update-service'),
    path('api/service/delete/<int:pk>/', ServicesDetailView.as_view({'delete': 'destroy'}), name='delete-service'),
    path("<int:pk>/", services_view, name='services_view'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/models.py
from django.db import models


class About(models.Model):
    company_name = models.CharField(max_length=255)
    title = models.TextField()
    description = models.TextField()
    logo1 = models.ImageField(upload_to='images/', null=True, blank=True)
    logo2 = models.ImageField(upload_to='images/', null=True, blank=True)
    side_image = models.ImageField(upload_to='images/', null=True, blank=True)
    telegram_id = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField()


class Certificate(models.Model):
    title = models.TextField()
    description = models.TextField()
    image = models.ImageField(upload_to='images/', null=True, blank=True)

home/models.py
from django.db import models
# from django.utils import timezone


# Create your models here.
class Slider(models.Model):
    image = models.ImageField(upload_to="images/", null=True, blank=True)
    title = models.TextField()
    description = models.TextField(blank=True, null=True)
    # datetime = models.DateTimeField(default=timezone.now)


class CEO(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to="images/", null=True, blank=True)
    description = models.TextField()

products/models.py
from django.db import models
from category.models import Category


# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    video_title = models.CharField(max_length=255, null=True, blank=True)
    video = models.FileField(upload_to='videos/', null=True, blank=True)
    categories = models.ManyToManyField(Category, related_name='products')

services/models.py
from django.db import models
from category.models import Category


# Create your models here.

class Services(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    categories = models.ForeignKey(Category, related_name='services', on_delete=models.CASCADE, null=True , blank=True)

about/views.py
from django.http import HttpResponse
from django.template import loader
from django.views.decorators.cache import cache_page
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework import status
from rest_framework.viewsets import ModelViewSet

from about.models import About, Certificate
from about.serializers import AboutSerializer, CertificateSerializer
from IranianShiningPhoenix.permissions import IsSuperUser
from category.models import Category


# Create your views here.
@cache_page(60 * 15)
def about_view(request):
    template = loader.get_template('about.html')
    category = Category.objects.all()
    certificate = Certificate.objects.all()
    context = {
        'category': category,
        'certificate' : certificate
    }

    return HttpResponse(template.render(context, request))


class AboutViewSet(viewsets.ModelViewSet):
    queryset = About.objects.all()
    serializer_class = AboutSerializer
    permission_classes = [IsSuperUser]

    # create a delete all method using action decorator, use http://127.0.0.1:8000/about/about-us/delete_all/ with
    # method DELETE to call delete_all function
    @action(detail=False, methods=['delete', ])
    def delete_all(self, request):
        count, _ = About.objects.all().delete()
        return Response(f"All {count} About instances were deleted.", status=status.HTTP_204_NO_CONTENT)


class CertificateView(ModelViewSet):
    queryset = Certificate.objects.all()
    serializer_class = CertificateSerializer

home/views.py
from django.http import HttpResponse
from django.views.decorators.cache import cache_page
from rest_framework import generics

from category.models import Category
from .models import Slider, CEO
from .serializers import SliderSerializer, CeoSerializer
from django.template import loader
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework import status
from IranianShiningPhoenix.permissions import IsSuperUser


@cache_page(60 * 15)
def home_view(request):
    template = loader.get_template('home.html')
    category = Category.objects.all()
    context = {
        'category': category
    }
    return HttpResponse(template.render(context, request))


class SliderViewSet(viewsets.ModelViewSet):
    queryset = Slider.objects.all()
    serializer_class = SliderSerializer
    permission_classes = [IsSuperUser]

    @action(detail=False, methods=['delete'])
    def delete_all(self, request):
        count, _ = Slider.objects.all().delete()
        return Response(f"All {count} Services instances were deleted.", status=status.HTTP_204_NO_CONTENT)


# class SliderListCreateAPIView(generics.ListCreateAPIView):
#     queryset = Slider.objects.all()
#     serializer_class = SliderSerializer
#
#
# class SliderRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
#     queryset = Slider.objects.all()
#     serializer_class = SliderSerializer

class CeoViewSet(viewsets.ModelViewSet):
    queryset = CEO.objects.all()
    serializer_class = CeoSerializer
    permission_classes = [IsSuperUser]

    @action(detail=False, methods=['delete'])
    def delete_all(self, request):
        count, _ = Slider.objects.all().delete()
        return Response(f"All {count} Services instances were deleted.", status=status.HTTP_204_NO_CONTENT)

# class CeoListCreateAPIView(generics.ListCreateAPIView):
#     queryset = CEO.objects.all()
#     serializer_class = CeoSerializer
#
#
# class CeoRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
#     queryset = CEO.objects.all()
#     serializer_class = CeoSerializer

products/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader
from django.views.decorators.cache import cache_page
from rest_framework import viewsets

from category.models import Category
from .models import Product
from .serializers import ProductSerializer
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework import status
from django_filters.rest_framework import DjangoFilterBackend
from IranianShiningPhoenix.permissions import IsSuperUser

# Create your views here.


@cache_page(60 * 15)
def product_view(request):
    template = loader.get_template('product.html')
    category = Category.objects.all()
    context = {
        'category': category
    }

    return HttpResponse(template.render(context, request))


class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['categories']
    permission_classes = [IsSuperUser]

    @action(detail=False, methods=['DELETE'])
    def delete_all(self, request):
        count, _ = Product.objects.all().delete()
        return Response(f"All {count} product instances were deleted.", status=status.HTTP_204_NO_CONTENT)

services/views.py
from django.http import HttpResponse
from django.template import loader
from django.views.decorators.cache import cache_page

from category.models import Category
from .models import Services
from .serializers import ServicesSerializer
from rest_framework.response import Response
from rest_framework import viewsets, generics, status
from IranianShiningPhoenix.permissions import IsSuperUser


@cache_page(60 * 15)
def services_view(request, pk):
    template = loader.get_template('services.html')
    category = Category.objects.all()
    services = Services.objects.filter(categories=pk)
    context = {
        'category': category,
        'services': services
    }
    return HttpResponse(template.render(context, request))


class ServicesCreateView(generics.CreateAPIView):
    queryset = Services.objects.all()
    serializer_class = ServicesSerializer
    permission_classes = [IsSuperUser]


class ServicesDetailView(viewsets.ViewSet):
    queryset = Services.objects.all()
    serializer_class = ServicesSerializer
    permission_classes = [IsSuperUser]

    def destroy(self, request, pk):
        try:
            services = Services.objects.get(pk=pk)
            services.delete()
            return Response(status=status.HTTP_204_NO_CONTENT)
        except Services.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

    def update(self, request, pk):
        try:
            services = Services.objects.get(pk=pk)
        except Services.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

        serializer = self.serializer_class(services, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">

    <script src="https://kit.fontawesome.com/1228ed801f.js" crossorigin="anonymous"></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js"></script>


    <title>{% block title %}درباره ی ققنوس درخشان ایرانیان{% endblock %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <style>

        html {
            position: relative;
        }

        footer {
            min-height: 50px;
        }

        .logoHolder {
            width: 100%;
            position: absolute;
            margin-top: 20px;
            display: inline-flex;
            z-index: 10 !important;
            direction: ltr;
            align-content: center;
            align-items: center;
            text-align: center;
            justify-content: center;
        }

        .logo {
            width: 112px;
            height: 100px;
            border-radius: 25px;
        }

        .footer-container {
            background: #3054B4;
            width: 100%;
            height: 250px;
            position: relative;
        }

        .footer-logo {
            height: 100%;
            float: right
        }


        .nav.navbar-nav li a {
            cursor: pointer;
        }

        .nav.navbar-nav a:hover {
            color: grey;
        }


        .dropdown-content a {
            width: auto;
            color: black;
            font-size: 16px;
            text-decoration: none;
            display: block;
        }


        .dropdown-menu li a {
            color: black;
            width: 100%;
            text-align: left;
        }

        /* Change color of dropdown links on hover */
        .dropdown-menu li a:hover {
            background-color: rgba(57, 149, 225, 0.1);
            color: black;
        }

        .container-footer {
            float: left;
            margin-top: 50px;
            margin-left: 50px;
            display: inline-grid;
        }


        .description {
            width: 100%;
            padding-left: 30%;
            padding-right: 30%;
            text-align: left;
            margin-top: 30px;
        }

        .selected {
            position: relative;
            width: 100%;
            height: auto;
            margin-top: 150px;
            text-align: center;
            justify-content: center;
        }

        .header {
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px 0;
            position: relative;
        }

        .header::before,
        .header::after {
            content: '';
            flex: 1;
            border-top: 2px solid #3054B4 !important; /* خط سفید */
            margin: 0 5px;
        }

        .header h3 {
            font-size: 1.8rem;
            font-weight: bold;
            text-transform: uppercase; /* حروف بزرگ */
            letter-spacing: 2px; /* فاصله بین حروف */
            margin: 0;
        }

        .vision-container {
            display: flex;
            position: relative;
            flex-wrap: nowrap; /* جلوگیری از شکستن سطر */
            overflow-x: auto;
            scroll-snap-type: x mandatory; /* حرکت نرم هنگام اسکرول */
            scrollbar-width: none; /* مخفی کردن اسکرول‌بار در فایرفاکس */
            scroll-behavior: smooth;

        }

        .vision-container::-webkit-scrollbar {
            display: none; /* مخفی کردن اسکرول‌بار در کروم و سافاری */
        }

        .vision-card {
            background: white !important;
            scroll-snap-align: center; /* مرکز چین شدن کارت‌ها */
            transition: transform 0.3s ease-in-out; /* انیمیشن برای حس بهتر */
            flex: 0 0 80%; /* هر کارت دقیقاً اندازه کل عرض صفحه */
            padding: 2rem;
            box-sizing: border-box;
        }


        @media screen and (max-width: 768px) {

            .selected {
                margin-top: 80px;
            }

            .description {
                width: 100%;
                padding-left: 10%;
                padding-right: 10%;
                margin-top: 30px;
            }

            .logo {
                width: 62px;
                height: 50px;
                border-radius: 25px;
            }

            .footer-container {
                height: 700px;
            }

            .footer-logo {
                width: 100%;
                height: 30%;
                display: inline-block;
                justify-content: center;
                align-items: center;
                align-content: center;
                text-align: center;
            }


            .navbar .navbar-nav {
                display: inline-block;
                float: none;
                vertical-align: top;
            }

            .navbar .navbar-collapse {
                text-align: center;
            }

            .container-footer {
                height: 200px;
                margin-top: 50px;
                margin-left: 10px;
                display: inline-block;
            }

            .copy {
                font-size: 12px;
            }
        }

    </style>
</head>
<body>

<nav class="navbar navbar-light navbar-expand-lg" style="background-color: #3054B4">

    <img src="{% get_media_prefix %}nav-log.png" style="width: 70px ; height: 63px" alt="logo">

    <!-- Toggler/collapsibe Button -->
    <button style="outline: none; box-shadow: none;" class="navbar-toggler justify-content-center" type="button"
            data-toggle="collapse" data-bs-toggle="collapse" data-target="#collapsibleNavbar"
            data-bs-target="#collapsibleNavbar" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="" role="button"><i class="fa fa-bars" aria-hidden="true" style="color:#e6e6ff"></i></span>
    </button>

    <!-- Navbar links -->
    <div class="collapse navbar-collapse justify-content-center" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link active text-white" aria-current="page" href="{% url 'home:view' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" href="#" role="button"
                   aria-expanded="false">Services</a>
                <ul class="dropdown-menu">
                    {% for x in category %}
                        {% if x.type == "services" %}
                            <li><a class="dropdown-item" href="{% url 'services:services_view' x.id %}">{{ x.name }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'product:view' %}">Product</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'contact:view' %}">Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'about:view' %}"
                   style="text-decoration: underline">About</a>
            </li>
        </ul>
    </div>
</nav>

<div class="logoHolder">

    <img alt="" src="{% get_media_prefix %}simple-logo.png" class="logo">

</div>


<h3 class="selected">Get to Know us</h3>

<p class="description">
    The Iranian shining Phoenix Group was established with the collective effort of aviation industry experts and with
    the aim of making profit by using the latest technologies and innovations of the world's aviation industry. The
    spread of some new methods and techniques in the world's aviation industry, such as dry washing or aircraft
    polishing, has led to the possibility of providing new and useful services in the aviation industry. On the other
    hand, the increase in the need for air transportation and passenger flights, the need for optimal use of resources
    in the presence of sanctions, as well as the need to attention to social responsibility, comply with environmental
    requirements, saving water consumption and etc., require the adoption of new solutions made it inevitable.
     
    <br>
    <br>
    This company is trying to open a new market in providing services to airlines by transferring and using new but
    simple, cost-effective and effective methods, materials and tools in Iran's aviation. A service that, in addition to
    increasing the safety and interest of passengers to use flight services on their travels, also results in reducing
    the costs and profitability of airlines.
</p>

<section class="section container py-5 text-center">
    <div class="header">
        <h3 class="fw-bold">Certificates</h3>
    </div>
    <p class="text-mute"></p>

    <!-- نوار زمان (Timeline) با اسکرول افقی -->
    <div class="vision-container d-flex gap-4 overflow-x-auto py-3 px-2 ">
        {% for x in certificate %}

            <div class="vision-card card p-4 shadow">
                <img src="/media/{{ x.image }}" class="card-img-top w-50 mx-auto" alt="{{ x.title }}">
                <div class="card-body">
                    <h5 class="card-title">{{ x.title }}</h5>
                    <p class="card-text">{{ x.description }}</p>
                    <a href="/media/{{ x.image }}" data-lightbox="certificates" data-title="{{ x.title }}" class="btn btn-primary">View</a>
                </div>
            </div>

        {% endfor %}

    </div>
</section>

<footer>

    <div class="footer-container">

        <div class="footer-logo">
            <img class="img-responsive" style="width: 256px ; height: 210px ; margin-top: 40px"
                 src="{% get_media_prefix %}nav-log.png"
                 alt="">
        </div>

        <div class="container-footer">
            <div style="display: inline-flex ; direction: ltr">
                <i class="fa-regular fa-envelope"
                   style="color: #ffffff; font-size: 30px">
                </i>
                <h5 style="color:white ; margin-left: 5px">
                    info@iranianshiningphoenix.com
                </h5>
            </div>

            <div style="display: inline-flex ; direction: ltr ; margin-top: 20px">
                <i class="fa-brands fa-telegram"
                   style="color: #ffffff; font-size: 30px"></i>
                <h5 style="color:white ; margin-left: 5px">
                    @iranianshiningphoenix
                </h5>
            </div>

            <div style="display: inline-flex ; direction: ltr ; margin-top: 20px">
                <i class="fa-brands fa-whatsapp"
                   style="color: #ffffff; font-size: 30px"></i>
                <h5 style="color:white ; margin-left: 5px">
                    +447377002350
                </h5>
            </div>

        </div>
    </div>

    <!-- Copyright -->
    <div class="p-3 copy" style="background: #142657 ; color: #B1B2B2">&copy;<span id="year"
                                                                                   style="font-family: Cambria, 'Hoefler Text', 'Liberation Serif', Times, 'Times New Roman', 'serif'">2024</span><a
            href="https://phoenixfamily.co/" style="color: #B1B2B2 ; text-decoration: none"> PhoenixFamily. All rights
        reserved.</a>
        <a href="//www.instagram.com/phoenixfamily.co?igsh=ZzRpb2owOHdnMWd5"
           style="right: 0 ; position: absolute ; margin-right:15px">
            <i class="fa-brands fa-instagram" style="color: #ffffff ; font-size: 30px"></i>
        </a>
        <a href="//linkedin.com/company/phoenixfamily" style="right: 0 ; position: absolute ; margin-right:55px">
            <i class="fa-brands fa-linkedin" style="color: #ffffff ; font-size: 30px"></i>
        </a>
        <span style=" float:right ;right: 0;margin-right: 80px ; position: relative">Follow us:</span>
    </div>
    <!-- Copyright -->
</footer>
</body>
</html>

templates/main.html
{% extends "admin/base_site.html" %}
{% load static %}
{% block extrahead %}
    <link rel="shortcut icon" href="{% get_media_prefix%}logo.jpg" />
{% endblock %}